[tool.poetry]
name = "ansible-generator"
version = "1.1.0"
description = ""
authors = ["Kevin Kirsche <kev.kirsche@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.3"
ansible = "^2.7"
raven = "^6.10"

[tool.poetry.dev-dependencies]
pytest = "^4.2"
pandoc = "^1.0"
coverage = "^4.5"
check-manifest = "^0.37.0"
black = { version = "^18.3-alpha.0", python = "^3.6" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
